controller_list:
  - name: sawyer_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints:
      - right_j0
      - right_j1
      - right_j2
      - right_j3
      - right_j4
      - right_j5
      - right_j6
